### ISSUE TITLE
nice but..

### ISSUE THREAD

**Issue by steppenwolf7** [MicrosoftDocs/cpp-docs.pl-pl#2]
[docs are usefull, but it looks like robot translate it in to polish]

---
#### Szczegóły dokumentu

⚠ *Nie edytuj tej sekcji. Jest ona wymagana dla docs.microsoft.com ➟ Dołączanie problemu w usłudze GitHub.*

* ID: eda99bc7-483b-e53c-1035-886f4d0955f4
* Version Independent ID: a6fdba4d-53e4-9f1a-2352-bc68ef491069
* Content: [Przewodnik: Tworzenie tradycyjnych aplikacji Windows Desktop (C++)](https://docs.microsoft.com/pl-pl/cpp/windows/walkthrough-creating-windows-desktop-applications-cpp?view=vs-2017)
* Content Source: [docs/windows/walkthrough-creating-windows-desktop-applications-cpp.md](https://github.com/MicrosoftDocs/cpp-docs.pl-pl/blob/live/docs/windows/walkthrough-creating-windows-desktop-applications-cpp.md)
* Product: **visual-cpp**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by CeciAc** [comment]
Hello, @steppenwolf7 

Thank you for your feedback. The page in question has been machine-translated, which is not always perfectly understandable. We recently added a **"Read in English"** option on the right which allows you to switch to the English version without having to change the language settings.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
**"Read in English"**
