### ISSUE TITLE
remotePreBuildCommand

### ISSUE THREAD

**Issue by lmalek** [MicrosoftDocs/cpp-docs.pl-pl#4]
In Visual Studio Community 2019 "remotePreBuildCommand" does not fit to the JSON schema. However 
"remotePrebuildCommand" works fine. Please fix this documentation.

---
#### Szczegóły dokumentu

⚠ *Nie edytuj tej sekcji. Jest ona wymagana dla docs.microsoft.com ➟ Dołączanie problemu w usłudze GitHub.*

* ID: 296f6914-b366-1ab8-4c08-6d51fc7212fa
* Version Independent ID: 04aec2e0-f39a-2e52-6a09-354222d47146
* Content: [Konfigurowanie projektu CMake systemu Linux w programie Visual Studio](https://docs.microsoft.com/pl-pl/cpp/linux/cmake-linux-project?view=vs-2019#feedback)
* Content Source: [docs/linux/cmake-linux-project.md](https://github.com/MicrosoftDocs/cpp-docs.pl-pl/blob/live/docs/linux/cmake-linux-project.md)
* Product: **visual-cpp**
* Technology: **cpp-linux**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
@lmalek sorry about that! We fixed this in the English version last week and the change should propagate to Polish soon.

**Comment by CeciAc** [comment]
Hi @JasonCard 
As per the comment above, this was already fixed but not yet updated in the localized version.
Should we keep this issue open until then?
best

**Comment by JasonCard** [comment]
Hi @mikeblome, I didn't see any update to the English article regarding "remotePreBuildCommand", so could you please help to clarify what was fixed? Then we can confirm when the fix is propagated to localized versions.
cc @CeciAc

**Comment by mikeblome** [comment]
@JasonCard @CeciAc Sorry I had fixed it in another topic. It's fixed in this one now and should go live with tomorrow's publish.

**Comment by CeciAc** [comment]
Hi @mikeblome, 
Thank you for your feedback.
 
We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/pl-pl/cpp/linux/cmake-linux-project?view=vs-2019#feedback
We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.

Kind regards,
Microsoft DOCS International Team
