### ISSUE TITLE
Should the "not necessary" be replaced with "incorrect"?

### ISSUE THREAD

**Issue by desowin** [MicrosoftDocs/cpp-docs.pl-pl#5]
In the sentence "The underlying OS file handle is also closed by a call to _close, so it is not necessary to call the Win32 function CloseHandle on the original handle." I find the wording misleading.

Reading this sentence, I understand it, "you don't have to do CloseHandle() but if you do, then nothing wrong happens". However, if you call _close() on the descriptor returned by _open_osfhandle() then both the descriptor and the HANDLE it took ownership of gets closed. Thus you shall not CloseHandle() on the HANDLE that was passed to _open_osfhandle(), as it is already closed. You might essentially close some other HANDLE if the value happened to be reused between the call to _close() and CloseHandle().

---
#### Szczegóły dokumentu

⚠ *Nie edytuj tej sekcji. Jest ona wymagana dla docs.microsoft.com ➟ Dołączanie problemu w usłudze GitHub.*

* ID: a25d8611-6401-b7b6-7df9-00fc9ee3987a
* Version Independent ID: 0a3f89eb-3b0c-7a1e-16c0-f394915c3837
* Content: [_open_osfhandle](https://docs.microsoft.com/pl-pl/cpp/c-runtime-library/reference/open-osfhandle?view=vs-2019#feedback)
* Content Source: [docs/c-runtime-library/reference/open-osfhandle.md](https://github.com/MicrosoftDocs/cpp-docs.pl-pl/blob/live/docs/c-runtime-library/reference/open-osfhandle.md)
* Product: **visual-cpp**
* Technology: **cpp-ucrt**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/cpp-docs #1022](https://github.com/MicrosoftDocs/cpp-docs/issues/1022) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @desowin

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/cpp-docs/issues/1022

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
